### Importing libraries

In [1]:
import numpy as np
from scipy.stats import chi2_contingency

### Chi-Squared
In this example, the test assesses whether there is a significant difference among men and women that watch a movie. The matrix has the following structure:
- Lines represent men and women, respectively;
- Columns represent the features "watch" and "don't watch", respectively.

In [2]:
movie = np.array([[19, 6], [43, 32]])
movie

array([[19,  6],
       [43, 32]])

Test execution.

In [3]:
# the second element is the p-value
# the p-value is bigger than 0.05 and, therefore, there is no evidence of a significant difference
# null hypothesis: there is no a significant difference
chi2_contingency(movie)

(2.037351443123939,
 0.15347667161786666,
 1,
 array([[15.5,  9.5],
        [46.5, 28.5]]))

New matrix with new values.

In [4]:
movie2 = np.array([[22, 3], [43, 32]])
movie2

array([[22,  3],
       [43, 32]])

In [5]:
# in this scenario, the p-value is lesser than 0.05 and, therefore, it's possible to reject the null hypothesis
# there is a significant difference
chi2_contingency(movie2)

(6.461538461538461,
 0.011023416388221425,
 1,
 array([[16.25,  8.75],
        [48.75, 26.25]]))